version: '3.8'

services:
  frontend:
    command: npm run dev
    build: ./game-client/
    ports:
      - 5173:5173

  app:
    build: ./
    command: bash -c "./wait-for-postgres.sh db && uvicorn app:app --proxy-headers --host 0.0.0.0 --port 8000"
      # - alembic upgrade head
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
      - HOST=app
      - DB_HOST=db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432